# Generated by Django 4.2.5 on 2023-10-06 08:42

import apps.user.validators
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_baseusermodel_managers_baseusermodel_region_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseusermodel',
            name='email_kk',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='email_ru',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='password_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='password_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='phone_number_kk',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.user.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='phone_number_ru',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[apps.user.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='username_kk',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='username_ru',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
